[package]
name = "smolBSD-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { version = "0.2", default-features = false }
ratatui = { version = "0.29", default-features = false, features = ["crossterm"] }
